services:

  postgis:
    tty: true
    build: .
    ports:
      - "5432:6543"
    restart: always
    environment:
      POSTGRES_DB: gis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: |
      postgres
      -c log_statement=all
      -c log_destination=stderr
      -c log_min_messages=info
      -c log_min_error_statement=info
      -c log_min_duration_statement=0
      -c log_connections=on
      -c log_disconnections=on
      -c log_duration=on
      -c log_line_prefix='%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '
      -c logging_collector=off
    volumes:
      - ./postgis-data:/var/lib/postgresql/data
      - ./maps:/opt/maps